program: sweep_interface.py
method: grid
name: clean
metric:
    name: bkd_acc
    goal: maximize
parameters:
    attack_type:
        value: 'Our'  
    dataset:
        value: 'cifar10' 
    in_channels:         
        value: 3
    image_size:         
        value: 32
    model:
        value: 'resnet18'
    agg_method:
        value: 'avg' # avg/clip/multi_krum/crfl/foolsgold/flame/feddmc/indicator/alignins
    is_poison:
        value: true
    load_benign_model:
        value: true
    seed:
        value: 0
    lr:
        value: 0.01
    gamma:
        value: 1
    lr_method:
        value: 'linear' 
    target_lr:
        value: 0.02
    momentum: 
        value: 0.9
    decay: 
        value: 0.0005
    batch_size:
        value: 64
    test_batch_size:
        value: 1024
    num_worker:
        value: 0
    poison_start_epoch:
        value: 1900 
    epochs:          
        value: 3101
    poison_epochs:   
        value: 100
    num_total_participants:   
        value: 100            
    num_adversaries:          
        value: 1
    num_sampled_participants: 
        value: 10
    sample_method:             
        value: 'random'
    sample_poison_ratio:   
        value: 0
    dirichlet_alpha:
        value: 0.9    
    retrain_times:
        value: 2
    attacker_retrain_times:
        value: 2
    save_every:               
        value: 3333
    attacker_method:
        value: 'sin-adv'
    malicious_update_method:
        value: 'label'
    clip_factor:
        value: 1
    attacker_lr_decay:
        value: 5
    target_class:
        value: 2        
    bkd_ratio:
        value: 0.25      
    trigger_outter_epochs:  
        value: 200
    trigger_lr:
        value: 0.01
    adv_loss:
        value: 'ce'
    dm_type:
        value: 'none'
    dm_adv_epochs:     #对抗模型训练轮数
        value: 5
    dm_adv_K:
        value: 1
    dm_adv_model_count:
        value: 1
    noise_model_count:
        value: 9
    noise_loss_lambda:
        value: 0.01
    wp_factor:
        value: 0.05
    trigger_epsilon:
        value: 2.0

#============ours_attacker相关参数=============
    SupCon_round1:    
        value: 2     
    SupCon_round2:
        value: 2    
    scale_weight:
        value: 6    
    down_scale_weight:
        value: 1    
    trigger_size:
        value: 49   
    is_Blend:
        value: False 
    blend_ratio:
        value: 1.0
    train_classifier:
        value: True  

#============Superparameter for Ablation Study=============
    is_optimize_mask:
        value: true
    is_optimize_trigger:
        value: true
    is_supcon:
        value: true
    two_stage_training:  
        value: true
