program: sweep_interface.py
method: grid
name: clean
metric:
    name: bkd_acc
    goal: maximize
parameters:
    attack_type:
        value: 'Our'  # A3FL/BadNets/Chameleon/Neurotoxin/Our
    dataset:
        value: 'cifar10' 
    in_channels:         
        value: 3
    image_size:         
        value: 32
    model:
        value: 'vgg11_bn'
        # value: 'resnet18'
    agg_method:
        value: 'avg' # avg/clip/multi_krum/crfl/foolsgold/flame/feddmc/indicator/alignins
    is_poison:
        value: true
    load_benign_model:
        value: true
    seed:
        value: 0
    lr:
        value: 0.01
    gamma:
        value: 1
    lr_method:
        value: 'linear' # linear/exp/warmup_cosine
    target_lr:
        value: 0.02
    momentum: 
        value: 0.9
    decay: 
        value: 0.0005
    batch_size:
        value: 64
    test_batch_size:
        value: 1024
    num_worker:
        value: 0
    poison_start_epoch:
        value: 1900 #  ←  随时准备攻击，但只有在is_poison为True时才会真正开始攻击
    epochs:          # 总的训练轮次
        value: 3101
    poison_epochs:   #===攻击训练轮次===
        value: 100
    num_total_participants:    #参与FL的总客户端数
        value: 100            
    num_adversaries:           #恶意客户端数
        value: 1
    num_sampled_participants:  #每轮参与FL的客户端数
        value: 10
    sample_method:             #客户端选择策略
        value: 'random'
    sample_poison_ratio:   #random_update中每轮参与FL的恶意客户端数
        value: 0
    dirichlet_alpha:
        value: 0.9    # 狄利克雷分布参数
    retrain_times:
        value: 2
    attacker_retrain_times:
        value: 2
    save_every:                #每隔多少轮保存一次模型
        value: 3333
    attacker_method:
        value: 'sin-adv'
    malicious_update_method:
        value: 'label'
    clip_factor:
        value: 1
    attacker_lr_decay:
        value: 5
    target_class:
        value: 2         # 目标攻击类别
    bkd_ratio:
        value: 0.25      # 每轮训练样本的中毒率
    trigger_outter_epochs:  #===寻找最优触发器的总训练轮次===
        value: 200
    trigger_lr:
        value: 0.01
    adv_loss:
        value: 'ce'
    dm_type:
        value: 'none'
    dm_adv_epochs:     #对抗模型训练轮数
        value: 5
    dm_adv_K:
        value: 1
    dm_adv_model_count:
        value: 1
    noise_model_count:
        value: 9
    noise_loss_lambda:
        value: 0.01
    wp_factor:
        value: 0.05
    trigger_epsilon:
        value: 2.0

#============ours_attacker相关参数=============
    SupCon_round1:    
        value: 2     # Encoder部分训练
    SupCon_round2:
        value: 2     # 分类器部分训练
    scale_weight:
        value: 6     # 提高中毒图像与促进者的权重（攻击标签对应的样本）
    down_scale_weight:
        value: 1     # 降低中毒图像与非促进者的权重（源类别对应的样本）
    trigger_size:
        value: 49   # DPOT掩码像素数量（如100，约占32x32图像的10%）
    is_Blend:
        value: False  # 是否使用Blend触发器注入方式，False为替换方式，True为Blend方式
    blend_ratio:
        value: 1.0
    # ----params for Ablation Study----
    train_classifier:
        value: True  # 是否训练分类器阶段，True时两阶段都训练，False时只训练Encoder阶段
    

#============Indicator聚合方法相关参数=============
    # 水印检测轮次相关参数
    watermarking_start_round:
        value: 0  # 开始进行水印检测的轮次
    watermarking_end_round:
        value: 3000  # 结束水印检测的轮次
    watermarking_round_interval:
        value: 1    # 水印检测的间隔轮次
    # 水印注入相关参数
    watermarking_mu:
        value: 0.1  # 水印损失函数中的权重系数
    global_lr:
        value: 0.0001 # 水印注入时的学习率
    global_momentum:
        value: 0.9   # 水印注入时的动量
    global_weight_decay:
        value: 0.0005 # 水印注入时的权重衰减
    global_lr_gamma:
        value: 0.1   # 学习率衰减系数
    global_retrain_no_times:
        value: 50   # 水印注入的训练轮次
    global_projection_norm:
        value: 0.8   # 参数投影的范数约束
    # 恶意客户端检测相关参数
    VWM_detection_threshold:
        value: 95.0  # 水印检测的阈值，高于此值被认为是恶意客户端
    replace_original_bn:
        value: true  # 是否在检测时使用原始BN层参数
    # 模型聚合相关参数
    eta:
        value: 1.0   # 聚合时的学习率

#============Our Method Ablation Study=============
    is_optimize_mask:
        value: true
    is_optimize_trigger:
        value: true
    is_supcon:
        value: true
    two_stage_training:  ### 后门注入时是否先进行良性训练
        value: true
